apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: node:0.10.40
        command: ['/bin/sh', '-c']
        args: ['cd /home && git clone https://github.com/Sadathossain/helloworld_localdev_vagrant.git demo && cd demo/ && npm install && sed -i -- ''s/localhost/mongo/g'' server.js && node server.js']
        name: web
        ports:
        - containerPort: 3000
          name: http-server
